platform :ios, '13.0'

target 'MvvmSandboxApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MvvmSandboxApp
  pod 'R.swift'
  pod 'Swinject'
end
